# Generated by Django 2.2 on 2020-09-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobby_name', models.CharField(max_length=200)),
                ('Hobby_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
