# Generated by Django 2.2 on 2020-10-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_auto_20201005_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image',
        ),
    ]
