# Generated by Django 2.2 on 2020-10-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0004_remove_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://www.usnews.com/dims4/USNEWS/07be4c0/2147483647/thumbnail/640x420/quality/85/?url=http%3A%2F%2Fmedia.beam.usnews.com%2F46%2F19%2F5c6c54fb4c6f812dc85c20fc656a%2F141106-portfolio-stock.jpg', max_length=500),
        ),
    ]
