# Generated by Django 2.2 on 2020-10-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0005_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='Hobby_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image',
        ),
    ]
