# Generated by Django 2.2 on 2020-10-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0013_auto_20201005_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_image',
        ),
    ]
