# Generated by Django 2.2 on 2020-10-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0015_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='Hobby_image',
        ),
    ]
