# Generated by Django 2.2 on 2020-10-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0016_remove_hobby_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='Hobby_image',
            field=models.CharField(default='https://fjwp.s3.amazonaws.com/blog/wp-content/uploads/2020/02/29113959/hobby-money-1024x512.png', max_length=500),
        ),
    ]
